formats: []

build:
  image: latest
  apt_packages:
    - libasound-dev
    - portaudio19-dev
    - libportaudio2
    - libportaudiocpp0
    - ffmpeg
    - libav-tools

python:
  version: 3.7
  pip_install: true
  extra_requirements:
    - docs