name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      with:
        - python-version: 3.8
      - uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: false
          black_args: ". --check --line-length 120"