name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: run linter
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: false
          black_args: ". --check --line-length 120"